In [1]:
import pandas as pd

# Q1. Pandas version

In [2]:
pd.__version__

'2.2.3'

In [3]:
data = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

# Q2. Records count

In [4]:
data.describe().round(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
count              9704.00        9222.00     8996.00         9704.00   
mean                199.71           3.96      149.66         3001.28   
std                  49.46           2.00       29.88          497.89   
min                  10.00           0.00       37.00          952.68   
25%                 170.00           3.00      130.00         2666.25   
50%                 200.00           4.00      149.00         2993.23   
75%                 230.00           5.00      170.00         3334.96   
max                 380.00          13.00      271.00         4739.08   

       acceleration  model_year  num_doors  fuel_efficiency_mpg  
count       8774.00     9704.00    9202.00              9704.00  
mean          15.02     2011.48      -0.01                14.99  
std            2.51        6.66       1.05                 2.56  
min            6.00     2000.00      -4.00                 6.20  
25%           13.30     2006.00      -1.00                13.27  
50%           15.00     2012.00       0.00                15.01  
75%           16.70     2017.00       1.00                16.71  
max           24.30     2023.00       4.00                25.97

# Q3. Fuel types

In [5]:
data.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [6]:
data['fuel_type'].nunique()

2

In [7]:
data['fuel_type'].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

# Q4. Missing values

In [8]:
data.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

# Q5. Max fuel efficiency

In [9]:
cars_asia = data[data['origin'] == 'Asia']

In [10]:
cars_asia['fuel_efficiency_mpg'].max()

23.759122836520497

# Q6. Median value of horsepower

In [11]:
data['horsepower'].median()

149.0

In [12]:
mode = data['horsepower'].mode().iloc[0]
mode

152.0

In [13]:
data['horsepower'] = data['horsepower'].fillna(mode)

In [22]:
data['horsepower'].median()

152.0

# Q7. Sum of weights

In [15]:
import numpy as np

In [16]:
X = np.array(cars_asia[['vehicle_weight','model_year']].head(n=7))
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [17]:
XTX = np.dot(X.T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [18]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [19]:
first = np.dot(np.linalg.inv(XTX), X.T)
first

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [20]:
w = np.dot(first, y)
w.sum()

0.5187709081074026